---
title: Test Post
author: Fiona Spooner
date: '2019-11-01'
categories:
  - R
tags:
  - plot
slug: test-post
active: yes
advanced:
  css_class: ''
  css_style: ''
design:
  background: {}
  columns: '1'
  spacing: {}
headless: yes
weight: 1
widget: blank
---

[A test post to see if this website is working](https://sourcethemes.com/academic/docs/writing-markdown-latex/)

```{r setup, include=FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```


```{r}
library(leaflet)
library(htmltools)
```


```{r}
data(quakes)
head(quakes)
```


```{r}
pal <- colorNumeric(
  palette = "Reds",
  domain = quakes$mag)


leaflet(quakes) %>%  
  addProviderTiles("CartoDB.Positron") %>%
  setView(mean(quakes$long), mean(quakes$lat), zoom = 4)%>% 
  addCircleMarkers(lng=quakes$long, lat=quakes$lat,radius = quakes$mag, 
                   color = ~pal(quakes$mag), stroke = FALSE, fillOpacity = 0.7) %>% 
   addLabelOnlyMarkers(~long, ~lat, label = as.character(paste("Magnitude: ",quakes$mag))) 

```